###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-10-16 15:09:53
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-10-16 17:26:30
###############################################################

invokables :
	agent_data_timeline_template 	: Data/Template/AgentDataTimelineTemplate

	agent_data_search_template		: Data/Template/AgentDataSearchTemplate
	agent_data_view_template		: Data/Template/AgentDataViewTemplate
	agent_data_create_template		: Data/Template/AgentDataCreateTemplate
	agent_data_update_template		: Data/Template/AgentDataUpdateTemplate
	agent_data_delete_template		: Data/Template/AgentDataDeleteTemplate
shared:
	agent_data_search_template		: true
	agent_data_view_template		: true
	agent_data_create_template		: true
	agent_data_update_template		: true
	agent_data_delete_template		: true